### ISSUE TITLE
Reason for using mixin instead of overriding use or useOnBlock?

### ISSUE THREAD

**Issue by P03W** [LordDeatHunter/HarvestScythes#5]
Hey there,  I was recently asked to add support for your mod ([RPGStats#29](https://github.com/P03W/RPGStats/issues/29)) and as I went to look for where I could mixin or listen for your item being used, I noticed that your injecting at Item.use, is there any reason for this?

It makes compatibility harder (but not impossible) so I was wondering if there was a reason behind it, as opposed to simply putting your behavior in your already existing item class

**Comment by LordDeatHunter** [comment]
Ah, thanks for mentioning this. The scythe tools were part of my first (unreleased) mod, so I just moved everything from there without changing too much.
I'm leaving some parts of the mixin, because I want to check for NBT data, so it's compatible with Smithee, until I think of something better.
I will push a new version later tonight. I just gotta fix some other things.

**Comment by P03W** [comment]
Alright, thanks for the explanation!

**Comment by LordDeatHunter** [comment]
I pushed the update on git and uploaded a build on CF. Hope this helps :)

**Comment by P03W** [comment]
having some issues with jitpack but it def looks far easier (Looks like ill only need 2 files instead of 5-7 :p), thanks much!

**Comment by LordDeatHunter** [comment]
I recommend CurseMaven. That's what I use personally.
